### ISSUE TITLE
Linker Errors on Ubuntu 11.10

### ISSUE THREAD

**Issue by GoogleCodeExporter** [RoboCup-SSL/ssl-vision#16]
```
Hi All,

I've experienced some strange behaviors while trying to compile r198 on Ubuntu 
11.10. 

After upgrading to Ubuntu 11.10 from 11.04, I faced to many linker errors while 
trying to compile SSL-Vision. I found out that the $QT_LIBRARIES variable in 
the CMakeList.txt points to wrong place, /usr/lib instead of currect 
/usr/lib/i386-linux-gnu/. This seems like a upgrade problem/bug.

I started again with a fresh install of Ubuntu 11.10 with all SSL-Vision 
required libraries installed. This time the $QT_LIBRARIES pointed to the 
correct place, however I receive this strange error while doing `make`:

[ 60%] Building CXX object CMakeFiles/client.dir/src/client/main.cpp.o
Linking CXX executable bin/client
libsslvision.a(robocup_ssl_client.cpp.o): In function 
`RoboCupSSLClient::RoboCupSSLClient(int, std::basic_string<char, 
std::char_traits<char>, std::allocator<char> >, std::basic_string<char, 
std::char_traits<char>, std::allocator<char> >)':
robocup_ssl_client.cpp:(.text+0x27): undefined reference to 
`QMutex::QMutex(QMutex::RecursionMode)'
robocup_ssl_client.cpp:(.text+0xc3): undefined reference to `QMutex::~QMutex()'
libsslvision.a(robocup_ssl_client.cpp.o): In function 
`RoboCupSSLClient::~RoboCupSSLClient()':
robocup_ssl_client.cpp:(.text+0x127): undefined reference to `QMutex::~QMutex()'
robocup_ssl_client.cpp:(.text+0x15d): undefined reference to `QMutex::~QMutex()'
collect2: ld returned 1 exit status
make[2]: *** [bin/client] Error 1
make[1]: *** [CMakeFiles/client.dir/all] Error 2
make: *** [all] Error 2

```

Original issue reported on code.google.com by `mani.mon...@gmail.com` on 14 Oct 2011 at 11:25
